### ISSUE TITLE
Reduce size of bigWig files produced

### ISSUE THREAD

**Issue by jma1991** [Ensembl/WiggleTools#17]
Why is the size of a bigWig file produced by the diff command so large compared to the input files? For example, I have two bigWig files of size 173M and 156M and the subtracted bigWig produced is 2.2G

`wiggletools diff treatment.bigWig control.bigWig > subtracted.bigWig`

Is there a setting I can use to reduce the file size?

**Comment by dzerbino** [comment]
Hello jma1991, this is because WT outputs in uncompressed [wiggle](https://genome.ucsc.edu/goldenpath/help/wiggle.html) format, not compressed [bigWig files](https://genome.ucsc.edu/goldenpath/help/bigWig.html).

If you run [wigToBigWig](https://wiki.gacrc.uga.edu/wiki/WigToBigWig) on WT's output, you should get a much smaller file.
